# Docs for the Azure Web Apps Deploy action: https://github.com/Azure/webapps-deploy
# More GitHub Actions for Azure: https://github.com/Azure/actions

name: Build and deploy container app to Azure Web App - BellezaMarinaCo2024

on:
  push:
    branches:
      - master
  workflow_dispatch:

jobs:
  build:
    runs-on: 'ubuntu-latest'

    steps:
    - uses: actions/checkout@v2

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2

    - name: Log in to registry
      uses: docker/login-action@v2
      with:
        registry: https://index.docker.io/v1/
        username: ${{ secrets.AzureAppService_ContainerUsername_3f1a471299b941ae89006af316607328 }}
        password: ${{ secrets.AzureAppService_ContainerPassword_f099c30b898348559dd4b81c70f9c6fe }}

    - name: Build and push container image to registry
      uses: docker/build-push-action@v3
      with:
        push: true
        tags: index.docker.io/${{ secrets.AzureAppService_ContainerUsername_3f1a471299b941ae89006af316607328 }}/mcr.microsoft.com/azure-app-service/windows/parkingpage:${{ github.sha }}
        file: ./Dockerfile

  deploy:
    runs-on: ubuntu-latest
    needs: build
    environment:
      name: 'production'
      url: ${{ steps.deploy-to-webapp.outputs.webapp-url }}

    steps:
    - name: Deploy to Azure Web App
      id: deploy-to-webapp
      uses: azure/webapps-deploy@v2
      with:
        app-name: 'BellezaMarinaCo2024'
        slot-name: 'production'
        publish-profile: ${{ secrets.AzureAppService_PublishProfile_86b6ade9f9714a9fadf649b6ea1e0ee8 }}
        images: 'index.docker.io/${{ secrets.AzureAppService_ContainerUsername_3f1a471299b941ae89006af316607328 }}/mcr.microsoft.com/azure-app-service/windows/parkingpage:${{ github.sha }}'